# Ignore false positive from Rails' ActionText and ActiveStorage
ActionText::RichText:
  enabled: false
ActiveStorage::Attachment:
  enabled: false
ActiveStorage::Blob:
  enabled: false
ActiveStorage::VariantRecord:
  enabled: false
Admin:
  index_admins_on_reset_password_token:
    UniqueIndexChecker:
      enabled: false
  password:
    ColumnPresenceChecker:
      enabled: false
