

require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rails
  - rubocop-faker

AllCops:
  TargetRubyVersion: 3.1.2
  TargetRailsVersion: 7.0.3
  NewCops: enable


Style/Documentation:
  Enabled: true
  Exclude:
    - app/controllers/**/*
    - app/helpers/application_helper.rb
    - config/**/*
    - db/**/*

Metrics/MethodLength:
  Enabled: true
  Exclude:
    - db/**/*
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - db/**/*
