require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rails
  - rubocop-faker
  - rubocop-thread_safety
  - rubocop-factory_bot

AllCops:
  TargetRubyVersion: 3.1.3
  TargetRailsVersion: 7.0.4
  NewCops: enable

# ===================== Rails ====================
Style/Documentation:
  Enabled: true
  Exclude:
    - app/controllers/**/*
    - app/helpers/application_helper.rb
    - app/mailers/application_mailer.rb
    - app/models/application_record.rb
    - config/**/*
    - db/**/*