default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= Rails.application.credentials.dig(:db, :pool) %>
  username: <%= ENV['DB_USERNAME'] || Rails.application.credentials.dig(:db, :username) %>
  password: <%= ENV['DB_PASSWORD'] || Rails.application.credentials.dig(:db, :password) %>

development:
  <<: *default
  database: happy_parents_ua_development

test:
  <<: *default
  database: happy_parents_ua_test

production:
  <<: *default
  database: expertbox_production