default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= Rails.application.credentials.dig(:db, :pool) %>

development:
  <<: *default
  database: <%= Rails.application.credentials.dig(:db, :name) %>
  host: <%= Rails.application.credentials.dig(:db, :host) %>
  port: <%= Rails.application.credentials.dig(:db, :port) %>
  username: <%= Rails.application.credentials.dig(:db, :username) %>
  password: <%= Rails.application.credentials.dig(:db, :password) %>

test:
  <<: *default
  database: <%= Rails.application.credentials.dig(:db, :name) %>
  host: <%= Rails.application.credentials.dig(:db, :host) %>
  port: <%= Rails.application.credentials.dig(:db, :port) %>
  username: <%= Rails.application.credentials.dig(:db, :username) %>
  password: <%= Rails.application.credentials.dig(:db, :password) %>
  
production:
  <<: *default
  database: <%= Rails.application.credentials.dig(:db, :name) %>
  host: <%= Rails.application.credentials.dig(:db, :host) %>
  port: <%= Rails.application.credentials.dig(:db, :port) %>
  username: <%= Rails.application.credentials.dig(:db, :username) %>
  password: <%= Rails.application.credentials.dig(:db, :password) %>
