name: Linters check
on: [push]
jobs:
 lefthook:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      - run: echo "🍏 This job's status is ${{ job.status }}."

