name: Linters check
on: [push]
jobs:
 lefthook:
    runs-on: ubuntu-latest
    steps:
      uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
        with:
          ruby-version: '3.1.2'
      - name: Install dependencies
        run: bundle install
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      - run: echo "🍏 This job's status is ${{ job.status }}."
