name: Tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:12.2-alpine
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_HOST: localhost
          POSTGRES_DB: happy-parents_ua_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
      with:
        ruby-version: '3.1.0'
    - name: Install dependencies
      run: bundle install
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
    # - name: setup Database
    #   run: |
    #     bundle exec rake db:create
    #     bundle exec rake db:migrate
    # - name: Setup tmate session
      # uses: mxschmitt/action-tmate@v3
    - name: Run tests
      run: bundle exec rspec
